### ISSUE TITLE
Elaborar Diagrama de Sequência

### ISSUE THREAD

**Issue by ricardocanela** [UnBArqDsw/2020.1_G4_Vestibulandos#20]
**Descrição da issue**
Elaborar Diagrama de Sequência

**Tarefas**

- [x] Definir as sequências e representá-las no diagrama

**Critérios de aceitação**

- [x] Seguir as regras de UML apresentados nas video-aulas 
- [x] Deve estar de acordo com os requisitos elicitados até o momento

**Comment by frclba** [comment]
![Diagrama de Sequencia - Manter Usuario](https://user-images.githubusercontent.com/16293264/94344109-697a9b00-fff3-11ea-8c88-7e47f26ba8c9.jpg)
![Diagrama de Sequencia - Manter Usuario Administrador](https://user-images.githubusercontent.com/16293264/94344110-6aabc800-fff3-11ea-9b0c-3a8f1c89bbcb.jpg)
![Diagrama de Sequencia - Manter Questoes](https://user-images.githubusercontent.com/16293264/94344111-6b445e80-fff3-11ea-8005-8f1c08d1aaf3.jpg)
