### ISSUE TITLE
Instalar ambiente de desenvolvimento

### ISSUE THREAD

**Issue by ricardocanela** [UnBArqDsw/2020.1_G4_Vestibulandos#29]
**Descrição da issue**
Assegurar que todos os membros possuam ambiente de desenvolvimento devidamente instalado em suas máquinas para poderem realizar o desenvolvimento do Backend e do Frontend.

**Tarefas**

- [x] Criar o Docker para desenvolvimento dos servidores NET Core para Backend
- [ ] Instalar o Unity 3d na máquina de cada membro para Frontend

**Critérios de aceitação**

- [ ] Todos os membros devem ser capazes de desenvolver utilizando Docker para Backend
- [ ] Todos os membros devem ser capazes de desenvolver utilizando Unity para Frontend

**Comment by frclba** [comment]
Done 

- https://github.com/UnBArqDsw/2020.1_G4_Vestibulandos_Frontend
- https://github.com/UnBArqDsw/2020.1_G4_Vestibulandos_Backend
