### ISSUE TITLE
Iniciar projeto no Unity 3D para desenvolvimento Frontend

### ISSUE THREAD

**Issue by ricardocanela** [UnBArqDsw/2020.1_G4_Vestibulandos#32]
**Descrição da issue**
Iniciar projeto e configurações iniciais do Unity 3D

**Tarefas**

- [x] Planejar comunicação com os servidores
- [x] Implementar configurações iniciais do projeto

**Critérios de aceitação**

- [x] Deve ser definida e divulgada a versão do Unity 3D para desenvolvimento

**Comment by frclba** [comment]
- https://github.com/UnBArqDsw/2020.1_G4_Vestibulandos_Frontend
