### ISSUE TITLE
Desenvolver e evidenciar a utilização de Observer na classe Partida

### ISSUE THREAD

**Issue by ricardocanela** [UnBArqDsw/2020.1_G4_Vestibulandos#38]
**Descrição da issue**
Desenvolver e evidenciar a utilização de Padrão de Projeto GOF comportamental Observer na classe Partida. Lembrando que o motivo de escolha desse padrão é que os Jogadores estarão observando a Partida para imprimir na tela do front o acompanhamento do andamento dos jogos.  

**Tarefas**

- [ ] Implementar o Padrão de Projeto
- [ ] Documentar o motivo e o modo de utilização desse Padrão de Projeto
- [ ] Evidenciar na wiki com um trecho do código a implementação do Padrão de Projeto

**Critérios de aceitação**

- [ ] É necessário que se explique, documente e evidencie a implementação do padrão na Wiki.

**Comment by lksgs0** [comment]
Após implementação do padrão Observer e um estudo mais aprofundado do código do padrão Mediator foi descoberto a possibilidade de aplicar alguns conceito do padrão Observer dentro do padrão Mediator, assim sendo desnecessário o uso do primeiro padrão. Como o padrão Observer já foi implementado, será removido dando lugar ao padrão Mediator.
