### ISSUE TITLE
Elaborar storyboard

### ISSUE THREAD

**Issue by juliolitwin** [UnBArqDsw/2020.1_G4_Vestibulandos#4]
**Descrição da issue**
Fazer o storyboard a partir de como é explicado pela a técnica.

**Tarefas**

- [x] Elaborar o storyboard

**Critérios de aceitação**

- [x] Storyboard feito

**Comment by gleal17** [comment]
Storyboard finalizado. Priorização de requisitos a ser feita em outra issue.
