### ISSUE TITLE
Elaborar o Questionário

### ISSUE THREAD

**Issue by juliolitwin** [UnBArqDsw/2020.1_G4_Vestibulandos#5]
**Descrição da issue**
Criar um questionário para poder coletar informações.

**Tarefas**
- [X] Criar o formulário no Google Forms
- [ ] Compartilhar o formulário

**Critérios de aceitação**
- [ ] O formulário foi compartilhado

**Comment by gleal17** [comment]
Questionário não foi considerado uma alternativa que agregasse ao projeto, considerado desnecessário.
